version: '3.8'

services:
  asiaticesports:
    image: sujitkh94/asiaticesports:development
    ports:
      - "3000:3000"
    restart: always
    expose:
      - 3005
    volumes: 
      - development-data:/app

volumes: 
  development-data:
