version: '3.8'

services:
  asiaticesports:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    expose:
      - 3000
    volumes: 
      - development-data:/app

volumes: 
  development-data:
