version: '3.8'

services:
  asiaticesports-frontend-development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asiaticesports-frontend-development
    image: asiaticesports-frontend:development
    ports:
      - "3005:3000" 
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'   
          memory: '1024M' 
    volumes:
      - asiaticesports-frontend-development-data:/app
    networks:
      - development

volumes:
  asiaticesports-frontend-development-data:

networks:
  development:
