version: '3.8'

services:
  asiaticesports-frontend-development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asiaticesports-frontend-development
    image: asiaticesports-frontend:development
    ports:
      - "3000:3000"
    restart: always
    expose:
      - 3000
    volumes:
      - asiaticesports-frontend-development-data
      - .:/app
    networks: 
      - development

volumes: 
  asiaticesports-frontend-development-data:
networks: 
  development: