version: '3.8'

services:
  asiaticesports:
    image: -development:lastest
    ports:
      - "3000:3000"
    restart: always
    expose:
      - 3005  # Add more ports if needed
    volumes:
      - -development-data:/app
      # Add more volumes if needed

volumes: 
  -development-data:
