version: '3.8'

services:
  asiaticesports-frontend-development:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asiaticesports-frontend-development
    image: asiaticesports-frontend:development
    ports:
      - "3005:3000"  # Map host port 3005 to container port 3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limit to 0.5 CPU cores
          memory: '1024M'  # Limit to 512 megabytes of RAM
    volumes:
      - asiaticesports-frontend-development-data:/app
    networks:
      - development

volumes:
  asiaticesports-frontend-development-data:

networks:
  development:
